builds: 
  - 
    id: "sysup-notifier"
    main: cmd/sysup-notifier/sysup-notifier.go
    binary: sysup-notifier/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7

release:
  prerelease: auto
