name: Go Release Builder

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  go-release-builder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: stable
          
      - name: Debug Secret Presence
        run: |
          if [ -z "${{ secrets.RELEASE_TOKEN }}" ]; then
            echo "RELEASE_TOKEN ist LEER"
          else
            echo "RELEASE_TOKEN ist gesetzt, Länge: ${#RELEASE_TOKEN}"
          fi
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
